### ISSUE TITLE
matrix multiplication

### ISSUE THREAD

**Issue by nicolaspanel** [scijs/cwise#10]
Hi,

Could you share an example for computing matrix multiplication of 2 arrays using cwise (something like [numpy.dot](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html#numpy.dot))?

Best regards (and thanks for the great work!)

**Comment by rreusser** [comment]
Tensor-like operations aren't supported in cwise, but the [ndgemm](https://github.com/scijs/ndgemm) package handles that.

**Comment by nicolaspanel** [comment]
Tx a lot!
